---
  - name: Install Redis
    yum: state=present name=http://epel.mirrors.arminco.com/6/x86_64/redis-2.4.10-1.el6.x86_64.rpm
    sudo: yes
    notify: Restart Redis

  - name: Redis config
    copy: src=redis.conf dest=/etc/redis.conf
    sudo: yes
    notify: Restart Redis
