---
  - name: Install Redis
    apt: state=present name=redis-server
    sudo: yes
    notify: Restart Redis

  - name: Redis config
    copy: src=redis.conf dest=/etc/redis/redis.conf
    sudo: yes
    notify: Restart Redis

  - name: Ensure Redis is running
    service: name=redis-server state=started
    sudo: yes
