---
  - name: Add repository for nginx
    copy: 
      src=ansible-bootstrap-ngix.repo 
      dest=/etc/yum.repos.d/ansible-bootstrap-ngix.repo

  - name: Install Nginx
    yum: state=present name=nginx enablerepo=nginx
    sudo: yes
    notify: Restart Nginx

  - name: Nginx conf
    template: 
      src=nginx_default.conf
      dest=/etc/nginx/conf.d/default.conf
    sudo: yes
    notify: Restart Nginx

  - name: Edit /etc/hosts
    debug: msg=TODO

  - name: Check for Kibana directory
    file:
      state=link
      src=/usr/share/nginx/kibana-3.0.0milestone5
      dest=/usr/share/nginx/kibana
    register: kibana_dir_present

  - name: Download Kibana
    get_url: 
      url=https://download.elasticsearch.org/kibana/kibana/kibana-3.0.0milestone5.tar.gz
      dest=~/kibana.tar.gz
    sudo: yes
    when: kibana_dir_present.changed

  - name: Unzip Kibana
    shell: tar xf ~/kibana.tar.gz -C /usr/share/nginx
    sudo: yes
    when: kibana_dir_present.changed

  - name: Edit Kibana config
    template: 
      src=kibana_config.js
      dest=/usr/share/nginx/kibana/config.js
    sudo: yes

  - name: Change iptables 
    lineinfile: 
      dest=/etc/sysconfig/iptables 
      insertbefore="^-A INPUT -j REJECT.*" 
      line="-A INPUT -m state --state NEW -m tcp -p tcp --dport {{ item }} -j ACCEPT"
    sudo: yes
    notify: Restart iptables
    with_items:
    - 80
    - 443
