---
  - name: Install Nginx
    apt: state=present name=nginx
    sudo: yes
    notify: Restart Nginx

  - name: Nginx conf
    copy:
      src=nginx_kibana.conf
      dest=/etc/nginx/conf.d/kibana.conf
    sudo: yes
    notify: Restart Nginx

  - name: Check for Kibana installation
    file:
      state=file
      name=/usr/share/nginx/kibana-3.0.0milestone5/config.js
    register: kibana_install_present
    sudo: yes
    ignore_errors: true

  - name: Download Kibana
    get_url:
      url=http://download.elasticsearch.org/kibana/kibana/kibana-3.0.0milestone5.tar.gz
      dest=/tmp/kibana.tar.gz
      sha256sum=c17c3c86c57b249d5188125ed20a01cd97347d32fddcbe05a35a663b76020dc3
    sudo: yes
    when: kibana_install_present.state == 'absent'

  - name: Unzip Kibana
    shell: tar xf /tmp/kibana.tar.gz -C /usr/share/nginx
    sudo: yes
    when: kibana_install_present.state == 'absent'

  - name: Create Kibana directory link
    file:
      state=link
      src=/usr/share/nginx/kibana-3.0.0milestone5
      dest=/usr/share/nginx/kibana
    sudo: yes

  - name: Edit Kibana config
    template:
      src=kibana_config.js
      dest=/usr/share/nginx/kibana/config.js
    sudo: yes

  - name: Copy dashboards
    copy:
      src="{{ item }}"
      dest="/usr/share/nginx/kibana/app/dashboards/{{ item | basename }}"
    with_fileglob:
      - ./dashboards/*
    tags: copy_dashboards
    sudo: yes

  - name: Ensure Nginx is running
    service: name=nginx state=started
    sudo: yes
