---
  - name: Nginx conf
    template:
      src=nginx_kibana.conf.j2
      dest=/etc/nginx/sites-available/kibana.conf
    sudo: yes

  - name: Nginx conf link
    file:
      state=link
      dest=/etc/nginx/sites-enabled/kibana.conf
      src=/etc/nginx/sites-available/kibana.conf
    notify: Reload Nginx
    sudo: yes

  - name: Ensure the default Nginx site is not enabled
    file:
      state=absent
      name=/etc/nginx/sites-enabled/default
    notify: Reload Nginx
    sudo: yes

  - name: Check for Kibana installation
    file:
      state=file
      name=/usr/share/nginx/kibana-3.1.0/config.js
    register: kibana_install_present
    sudo: yes
    ignore_errors: true

  - name: Download Kibana
    get_url:
      url=https://download.elasticsearch.org/kibana/kibana/kibana-3.1.0.tar.gz
      dest=/tmp/kibana.tar.gz
      sha256sum=059a4b6b507b9ff771901d12035e499b0e8d1cae7d9e5284633e19da6c294e07
    sudo: yes
    when: kibana_install_present.state == 'absent'

  - name: Unzip Kibana
    shell: tar xf /tmp/kibana.tar.gz -C /usr/share/nginx
    sudo: yes
    when: kibana_install_present.state == 'absent'

  - name: Create Kibana directory link
    file:
      state=link
      src=/usr/share/nginx/kibana-3.1.0
      dest=/usr/share/nginx/kibana
    sudo: yes

  - name: Edit Kibana config
    template:
      src=kibana_config.js.j2
      dest=/usr/share/nginx/kibana/config.js
    sudo: yes

  - name: Copy dashboards
    copy:
      src="{{ item }}"
      dest="/usr/share/nginx/kibana/app/dashboards/{{ item | basename }}"
      mode=0644
      owner=root
      group=root
    with_fileglob:
      - ./dashboards/*
    tags: copy_dashboards
    sudo: yes

  - name: Ensure Nginx is running
    service: name=nginx state=started
    sudo: yes
