---
  - name: Install Nginx
    apt: state=present name=nginx
    sudo: yes
    notify: Restart Nginx

  - name: Nginx conf
    copy:
      src=nginx_kibana.conf
      dest=/etc/nginx/conf.d/kibana.conf
    sudo: yes
    notify: Restart Nginx

  - name: Check for Kibana directory
    file:
      state=link
      src=/usr/share/nginx/kibana-3.0.0milestone5
      dest=/usr/share/nginx/kibana
    register: kibana_dir_present
    sudo: yes

  - name: Download Kibana
    get_url:
      url=http://download.elasticsearch.org/kibana/kibana/kibana-3.0.0milestone5.tar.gz
      dest=~/kibana.tar.gz
    sudo: yes
    when: kibana_dir_present.changed

  - name: Unzip Kibana
    shell: tar xf ~/kibana.tar.gz -C /usr/share/nginx
    sudo: yes
    when: kibana_dir_present.changed

  - name: Edit Kibana config
    template:
      src=kibana_config.js
      dest=/usr/share/nginx/kibana/config.js
    sudo: yes

  - name: Ensure Nginx is running
    service: name=nginx state=started
    sudo: yes
