---
  - name: Nginx conf
    template:
      src=nginx_proxy_es.conf.j2
      dest=/etc/nginx/sites-available/nginx_proxy_es.conf
    sudo: yes

  - name: Nginx conf link
    file:
      state=link
      name=/etc/nginx/sites-enabled/nginx_proxy_es.conf
      src=/etc/nginx/sites-available/nginx_proxy_es.conf
    notify: Reload Nginx
    sudo: yes
