---
  - name: Install prerequisites
    apt:
      pkg={{item}}
      state=present
      update_cache=yes
    with_items:
      - python-apt
      - python-pycurl   # Not present on default installs, required for apt_repository
    sudo: yes

  - include: unattended-upgrades.yml
    sudo: yes

  - name: Update packages
    apt: upgrade=safe
    sudo: yes
