---
  - name: Check ubuntu mirror
    command: grep -E '^\s*deb(|-src)\s*http://us\.' /etc/apt/sources.list
    register: ubuntu_mirror
    ignore_errors: true

  - name: Select Dutch ubuntu mirror
    command: sed -ie "s/http:\/\/us/http:\/\/nl/" /etc/apt/sources.list
    when: ubuntu_mirror.rc == 0

  # - name: Reload apt cache
  #   apt: update_cache=yes

  # - name: Update packages
  #   apt: upgrade=safe

  - name: Install prerequisites
    apt:
      pkg={{item}}
      state=present
      update_cache=yes
    with_items:
      - python-apt
      - python-pycurl
