---
- name: Install unattended-upgrades
  apt:
    pkg=unattended-upgrades
    state=present

- name: Ensure unattended-upgrades is running
  service:
    name=unattended-upgrades
    state=running
    enabled=yes

- name: Enable periodic run of unattended-upgrades
  copy:
    src=apt-periodic.conf
    dest=/etc/apt/apt.conf.d/02periodic
    owner=root
    group=root
    mode=0644
