---
- name: Install dependencies
  apt: state=present name=openjdk-7-jre-headless
  sudo: yes

- name: Install Elasticsearch apt key
  apt_key:
    url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state=present
  sudo: yes

- name: Add Elasticsearch repository
  apt_repository:
    repo="deb http://packages.elasticsearch.org/elasticsearch/1.1/debian stable main"
    update_cache=yes
    state=present
  sudo: yes

- name: Install Elasticsearch
  apt:
    pkg=elasticsearch
    state=present
  sudo: yes

- name: Ensure data directory exists
  file:
    state=directory
    path=/opt/data/elasticsearch
    owner=elasticsearch
    group=elasticsearch
    mode=0755
  sudo: yes

- name: Elasticsearch configuration
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
  notify: Restart Elasticsearch
  sudo: yes

- name: Elasticsearch logging configuration
  copy:
    src=logging.yml
    dest=/etc/elasticsearch/logging.yml
  notify: Restart Elasticsearch
  sudo: yes

- name: Ensure Elasticsearch is running
  service: name=elasticsearch state=started
  sudo: yes
