---
  - name: Install dependencies
    yum: state=present name=java-1.7.0-openjdk
    sudo: true
    
  - name: Create /opt/logstash
    file: state=directory name=/opt/logstash
    sudo: yes

  - name: Grab Logstash
    sudo: yes
    get_url:
      url=https://download.elasticsearch.org/logstash/logstash/logstash-1.3.3-flatjar.jar
      dest=/opt/logstash/logstash-1.3.3-flatjar.jar
      sha256sum=a83503bd2aa32e1554b98f812d0b411fbc5f7b6b21cebb48b7d344474f2dfc6d
    notify: Restart Logstash

  - name: Install init script
    copy: src=logstash.sh dest=/etc/init.d/logstash mode=0744
    sudo: yes

  - name: Copy logstash.conf
    template: src=indexer.conf dest=/opt/logstash/logstash.conf
    sudo: yes
    notify: Restart Logstash
    tags: xxx
