---
- name: Install dependencies
  apt: state=present name=openjdk-7-jre-headless
  sudo: true

- name: Install Elasticsearch apt key
  apt_key:
    url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state=present
  sudo: yes

- name: Add Logstash repository
  apt_repository:
    repo="deb http://packages.elasticsearch.org/logstash/1.4/debian stable main"
    update_cache=yes
    state=present
  sudo: yes

- name: Install Logstash
  apt:
    pkg=logstash
    state=present
  sudo: yes

- name: Copy logstash.conf
  template:
    src=indexer.conf
    dest=/etc/logstash/conf.d/logstash.conf
    owner=logstash
    group=logstash
    mode=0644
  sudo: yes
  notify: Restart Logstash

- name: Start Logstash on boot
  lineinfile:
    state=present
    name=/etc/default/logstash
    line=START=yes
    regexp='^START=.*'
  sudo: yes

- name: Ensure Logstash is running
  service: name=logstash state=started
  sudo: yes
